spring:
  application:
    name: boot-security-plus
  # 기본 실행 지정
  profiles:
    active: dev
    # 배포할 때 Docker를 사용해서 prod로 지정하기
  # 커넥션 풀 관련 (참고 -> TIL하면 좋음)
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 10 # 최대 커넥션 수
      minimum-idle: 5 # 최소 유휴 커넥션 수
  # MyBatis 설정
  mybatis:
    #    mapper-locations: classpath:mapper/*.xml # 매퍼 XML 파일 위치 설정
    type-aliases-package: org.example.bootsecurityplus.model.domain # 도메인 객체 패키지 경로
    configuration:
      map-underscore-to-camel-case: true # 언더스코어 표기법을 카멜 케이스 표기법으로 자동 변환